version: "3"
services:
  selenium-hub:
    image: selenium/hub:4
    container_name: selenium-hub
    ports:
      - "4442:4444"
    expose: 
      - "4442:4444"
  chrome:
    image: selenium/node-chrome:93.0
    deploy:
      replicas: 3
    #    ports: # Not using node-chrome-debug image
      #- "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  firefox:
    image: selenium/node-firefox:92.0
    deploy:
      replicas: 3
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
